version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ppdb_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ppdb_smk
      MYSQL_USER: ppdb_user
      MYSQL_PASSWORD: ppdb_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ppdb_network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ppdb_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ppdb_user
      PMA_PASSWORD: ppdb_password
    ports:
      - "8080:80"
    networks:
      - ppdb_network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  ppdb_network:
    driver: bridge